CREATE TABLE "T_SUB_MEDIASHARE_DEVICE_INFO" 
   (	"CRM_ID" VARCHAR2(50 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(100 BYTE), 
	"MSISDN" VARCHAR2(100 BYTE), 
	 CONSTRAINT "T_MEDIASHARE_DEVICE_INFO_PK" PRIMARY KEY ("CRM_ID")
  );

alter table T_D_CNF_PLATFORM_DETAIL drop primary key;
alter table T_D_CNF_PLATFORM_DETAIL add constraint t_d_cnf_platform_detail_pk primary key ("SERVICE_ID", "SERVICE_TYPE", "VENDOR", "COMMAND_TYPE", "SUBS_TYPE", "TONE_TYPE");

Alter table T_D_CNF_PLATFORM_DETAIL ADD "TONE_TYPE" VARCHAR2(20 BYTE) DEFAULT -1 NOT NULL ENABLE;
Alter table t_d_cnf_notification_rule ADD "TONE_TYPE" VARCHAR2(20 BYTE) DEFAULT -1 NOT NULL ENABLE;
Insert into T_D_CNF_PLAN_MASTER (SERVICE_ID,SERVICE_TYPE,PLAN_ID,PLAN_DESC,NXT_PLN_ID,STATUS,PARENT_PLAN_ID,LIFECYCLE_ID,SERVICE_PRIORITY,START_DATETIME,END_DATETIME,AUTO_RENEWAL,TRY_N_BUY_FLAG,DISCOUNT_ID,SUBS_TYPE,PLAN,TYPE,FILE_RETRY_FLAG,DEACTIVATION_MODE,SEGMENT,PRIODICTY_PLAN,PRIODICTY_PERIOD,AUTO_REN_CATEGORY,RE_SUBS_ALLOWED,DYNAMIC_LIFE_CYCLE,DYNAMIC_LC_PRIORITY,TRYNBYE_CONSENT_REQ,FAIL_ACTION,EVERY_TIME_CHARGING,REVENUE_TYPE,REVENUE,RATING_ID,REVENUE_CYCLE,REMARKS,ADD_BY,ADD_ON,APPROVAL_BY,CIRCLE,BEARER,SERVICE_PROVIDER_ID,PROVIDER_ID,PLAN_GROUP,RENEWAL_BUNDLE_TYPE,TONE_TYPE,CALLBACK_URL_ACTIVE,CALLBACK_URL_PASSIVE,BASE_OFFER_ID,PACK_LIMIT,GIFTER_CONSENT,VALIDITY_APPROACH,VALIDITY_APPROACH_TYPE,VALIDITY_APPROACH_VALUE,PRIORITY,STACKED_QUEUED,PLAN_SPEC_IDS) values ('JMSHARE','Z0038','JB411','30 days free Trial All Songs','JB411','A','JB411','JB411_LS',1,to_date('01-05-14','DD-MM-RR'),to_date('31-12-20','DD-MM-RR'),'N','N','NA',0,'I','P','N','I',null,'N',0,'D','Y','N','N','N','N','N','NA',0,'N',0,'updatePlan','-1',to_timestamp('21-03-16 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'NA','BP~MC~RC~TC~MU~GJ~TN~KA~MH~WB~KO~KL~BR~AP~MP~NE~AS~UE~OR~PB',null,'RJIL','RJIL',null,'N','BS',null,null,null,null,null,'1',null,null,'0',null,null);
Insert into T_D_CNF_SERVICE_MASTER (SERVICE_ID,SERVICE_TYPE,SERVICE_DESC,SERVICE_NODE,INTEGRATION_TYPE,CALLBACK_REQUIRED,CALLBACK_URL_ACTIVE,CALLBACK_URL_PASSIVE,SERVICE_PROVIDER_ID,TELE_SERVICE_CODE,SERVICE_VALIDITY_TYPE,CHARGING_MODE,LINK,LINKED_SERVICE_ID,LINKED_SERVICE_TYPE,STATUS,POSTPAID_IDENTIFIER,CONSENT_REQ,IN_PARAM,INT_INTEGRATION,PLATFORM_SERVICE_TYPE,SERVICE_SUB_TYPE,COMPANY_CODE,SERVICE_GROUP,FEATURE_ID,TEMPLATE_ID,SUCCESS_TABLENAME,IN_PARAM1) values ('JMSCHILD','Z0038','Jio MS Child','RJIL','130','N','NA','NA',-1,-1,'O','S','Y','JMSHARE','Z0038','A','None','N',null,130,null,null,null,'DIG',null,'999991A',null,null);
Insert into T_D_CNF_SERVICE_MASTER (SERVICE_ID,SERVICE_TYPE,SERVICE_DESC,SERVICE_NODE,INTEGRATION_TYPE,CALLBACK_REQUIRED,CALLBACK_URL_ACTIVE,CALLBACK_URL_PASSIVE,SERVICE_PROVIDER_ID,TELE_SERVICE_CODE,SERVICE_VALIDITY_TYPE,CHARGING_MODE,LINK,LINKED_SERVICE_ID,LINKED_SERVICE_TYPE,STATUS,POSTPAID_IDENTIFIER,CONSENT_REQ,IN_PARAM,INT_INTEGRATION,PLATFORM_SERVICE_TYPE,SERVICE_SUB_TYPE,COMPANY_CODE,SERVICE_GROUP,FEATURE_ID,TEMPLATE_ID,SUCCESS_TABLENAME,IN_PARAM1) values ('JMSHARE','Z0038','Jio Media Share','RJIL','130','N','NA','NA',-1,-1,'E','S','N','NA','NA','A','None','N',null,130,null,null,null,'DIG',null,'999991A',null,null);


Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','RES','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','REMOTE');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSHARE','-1','ACT','REST','12000','12000','http://10.135.140.219:5003/ras','E',null,'Y','-1',null,'201','-1');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','ACT','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','REMOTE');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','DACT','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','REMOTE');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSHARE','-1','DACT','REST','12000','12000','http://10.135.140.219:5003/ras','E',null,'Y','-1',null,'201','-1');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','RES','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','LOCAL');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','ACT','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','LOCAL');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','DACT','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','LOCAL');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','SWI','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','REMOTE');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSHARE','-1','RES','REST','12000','12000','http://10.135.140.219:5003/ras','E',null,'Y','-1',null,'201','-1');
Insert into T_D_CNF_PLATFORM_DETAIL (SERVICE_TYPE,SERVICE_ID,VENDOR,COMMAND_TYPE,PROTOCOL,READ_TIME_OUT,CONNECT_TIME_OUT,URL,ENABLE,PLATFORM_FORMAT_ID,READ_HTTP_RESPONSE,SUBS_TYPE,RETRY_RESPONSE_CODES,SUCCESS_RESPONSE_CODE,TONE_TYPE) values ('Z0038','JMSCHILD','-1','SWI','SOAP','12000','12000','https://sitacsapp06.oss.sit.jio.com/ftacsws/acsws.asmx?wsdl','E',null,'Y','-1',null,'100','LOCAL');


select owner,object_type,status from all_objects where object_name = 'UTL_FILE';
select grantee from all_tab_privs where table_name = 'UTL_FILE';
select directory_name, directory_path from all_directories;
--/home/mbas/dpdir_1
select grantee, privilege from all_tab_privs where table_name = 'DPDIR';
create or replace directory back_proc_dir as '/home/mbas/Oracle/File_Logging';

declare
  fhandle  utl_file.file_type;
  v_logfile VARCHAR2(100);
BEGIN
  v_logfile := TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')||'_process.log';
     fhandle := utl_file.fopen(
                'DPDIR1' -- File location
               , v_logfile -- File name
                , 'w' -- Open mode: w = write.
                    );

    utl_file.put(fhandle, 'Hello world!'
                       || CHR(10));
   utl_file.put(fhandle, 'Hello again!');

    utl_file.fclose(fhandle);
  exception
    when others then
      dbms_output.put_line('ERROR: ' || SQLCODE
                        || ' - ' || SQLERRM);
   raise;
 end;
 /